name: Sandpack

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Update Sandpack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          # Fetch all git history so that yarn workspaces --since can compare with the correct commits
          # @link https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
          fetch-depth: 0
 
      - name: Update Code in Sandpack
        run: yarn gen:code
        
      - name: Update Version in Sandpack
        run: yarn gen:v

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: 'Version Sandpack'
          body: |
            Update Plate versions in Sandpack examples. Merge if it has no errors:
            
            - [Playground](https://plate.udecode.io/docs/playground) 
          commit-message: docs
          committer: GitHub <noreply@github.com>
          branch: docs/sandpack
          delete-branch: true
          assignees: zbeyens
