name: Sandpack

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Update Sandpack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # To run comparison we need more than the latest commit. Keep the fetch-depth relatively
          # high or set it to zero to get all commits from the git repo.
          # @link https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
          fetch-depth: 150

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4